stages:
  - build
  - deploy

variables:
  CONTAINER_IMAGE: ${CI_REGISTRY}/${CI_PROJECT_PATH}:${CI_BUILD_REF_NAME}_${CI_BUILD_REF}
  CONTAINER_IMAGE_LATEST: ${CI_REGISTRY}/${CI_PROJECT_PATH}:latest
  DOCKER_DRIVER: overlay2

  KUBECONFIG: /etc/deploy/config
  STAGING_NAMESPACE: app-stage

build:
  stage: release
  image: docker:20.10
  script:
    - cd ${APP_PATH}/release
    - docker login -u gitlab-ci-token -p ${CI_BUILD_TOKEN} ${CI_REGISTRY}
    - docker build -t ${CONTAINER_IMAGE} .
    - docker tag ${CONTAINER_IMAGE} ${CONTAINER_IMAGE_LATEST}
    - docker push ${CONTAINER_IMAGE}
    - docker push ${CONTAINER_IMAGE_LATEST}

deploy_staging:
  stage: deploy
  image: dtzar/helm-kubectl:3.7
  before_script:
    - echo ${kube_config} | base64 -d > ${KUBECONFIG}
    - kubectl config use-context stage
    - helm init --client-only
    - cd chart/litecoin
    - if [ ${DEPLOYS}  -eq 0 ]; then helm install --name=litecoin . --namespace=${STAGING_NAMESPACE}; else helm upgrade litecoin . --namespace=${STAGING_NAMESPACE}; fi
